apiVersion: v1
kind: Service
metadata:
  name: chat-call-service
spec:
  type: LoadBalancer
  selector:
    app: chat-call-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
