apiVersion: v1
kind: Service
metadata:
  name: chat-authorization-service
spec:
  selector:
    app: chat-authorization-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      