apiVersion: v1
kind: Service
metadata:
  name: chat-message-service
spec:
  type: LoadBalancer
  selector:
    app: chat-message-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
