server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: 'jdbc:postgresql://localhost:5432/chatWithMe-chat'
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
springdoc:
  model-converters:
    pageable-converter:
      enabled: true
  api-docs:
    path: /chatWithMe-chat
  swagger-ui:
    path: /doc
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: method
    syntax-highlight:
      theme: arta

